version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
